#!/bin/bash

set -e

area=$(slurp)

if [[ -z "$area" ]]; then
    notify-send "OCR Cancelled" "No area selected."
    exit 1
fi

grim -g "$area" /tmp/ocr.png

magick /tmp/ocr.png \
  -colorspace Gray \
  -resize 300% \
  -contrast-stretch 0x10% \
  -sharpen 0x1 \
  /tmp/ocr-pre.png

text=$(tesseract /tmp/ocr-pre.png stdout -l eng+ind --psm 6)

echo -n "$text" | wl-copy

if [[ -n "$text" ]]; then
    preview=$(echo "$text" | tr '\n' ' ' | cut -c1-80)
    notify-send "OCR Complete" "$preview"
else
    notify-send "OCR Failed" "No text detected."
fi

rm -f /tmp/ocr.png /tmp/ocr-pre.png