#!/bin/bash

set -e

grim -g "$(slurp)" /tmp/ocr.png

magick /tmp/ocr.png \
  -colorspace Gray \
  -resize 200% \
  -sharpen 0x1 \
  /tmp/ocr-pre.png

text=$(tesseract /tmp/ocr-pre.png stdout -l eng+ind)

echo -n "$text" | wl-copy

if [[ -n "$text" ]]; then
    preview=$(echo "$text" | tr '\n' ' ' | cut -c1-80)
    notify-send "OCR Complete" "$preview"
else
    notify-send "OCR Failed" "No text detected."
fi

rm -f /tmp/ocr.png /tmp/ocr-pre.png